//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.18444 版自动生成。
// 
#pragma warning disable 1591

namespace PMS.RLNWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RLNSWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class RLNSWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateRLNOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTempCrIdToCrIdOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RLNSWebService() {
            this.Url = global::PMS.Properties.Settings.Default.PMS_RLNWebService_RLNSWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateRLNCompletedEventHandler CreateRLNCompleted;
        
        /// <remarks/>
        public event UpdateTempCrIdToCrIdCompletedEventHandler UpdateTempCrIdToCrIdCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateRLN", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateRLN(string XML) {
            object[] results = this.Invoke("CreateRLN", new object[] {
                        XML});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateRLNAsync(string XML) {
            this.CreateRLNAsync(XML, null);
        }
        
        /// <remarks/>
        public void CreateRLNAsync(string XML, object userState) {
            if ((this.CreateRLNOperationCompleted == null)) {
                this.CreateRLNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateRLNOperationCompleted);
            }
            this.InvokeAsync("CreateRLN", new object[] {
                        XML}, this.CreateRLNOperationCompleted, userState);
        }
        
        private void OnCreateRLNOperationCompleted(object arg) {
            if ((this.CreateRLNCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateRLNCompleted(this, new CreateRLNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UpdateTempCrIdToCrId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateTempCrIdToCrId(string oldCrId, string newCrId) {
            object[] results = this.Invoke("UpdateTempCrIdToCrId", new object[] {
                        oldCrId,
                        newCrId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTempCrIdToCrIdAsync(string oldCrId, string newCrId) {
            this.UpdateTempCrIdToCrIdAsync(oldCrId, newCrId, null);
        }
        
        /// <remarks/>
        public void UpdateTempCrIdToCrIdAsync(string oldCrId, string newCrId, object userState) {
            if ((this.UpdateTempCrIdToCrIdOperationCompleted == null)) {
                this.UpdateTempCrIdToCrIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTempCrIdToCrIdOperationCompleted);
            }
            this.InvokeAsync("UpdateTempCrIdToCrId", new object[] {
                        oldCrId,
                        newCrId}, this.UpdateTempCrIdToCrIdOperationCompleted, userState);
        }
        
        private void OnUpdateTempCrIdToCrIdOperationCompleted(object arg) {
            if ((this.UpdateTempCrIdToCrIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTempCrIdToCrIdCompleted(this, new UpdateTempCrIdToCrIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void CreateRLNCompletedEventHandler(object sender, CreateRLNCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateRLNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateRLNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void UpdateTempCrIdToCrIdCompletedEventHandler(object sender, UpdateTempCrIdToCrIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTempCrIdToCrIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTempCrIdToCrIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591