/***********************************************************
 ** File Name : BaseDataDomain.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-14
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class BaseDataDomain
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
        private int m_Id;
        private string m_Name;
        private string m_Description;
        private DateTime m_CreateDate;
        private string m_CreateUser;
        private DateTime m_MaintainDate;
        private string m_MaintainUser; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public BaseDataDomain()
		{
			m_Id = 0; 
			m_Name = null ;
            m_Description = null; 
			m_CreateDate = new DateTime();
            m_CreateUser = null; 
			m_MaintainDate = new DateTime();
            m_MaintainUser = null;  
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
        public int Id
		{
			get { return m_Id; }
			set { m_IsChanged |= (m_Id != value); m_Id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Name
		{
			get { return m_Name; }
			set { m_IsChanged |= (m_Name != value); m_Name = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Description
		{
			get { return m_Description; }
			set { m_IsChanged |= (m_Description != value); m_Description = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string CreateUser
		{
			get { return m_CreateUser; }
			set { m_IsChanged |= (m_CreateUser != value); m_CreateUser = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public DateTime MaintainDate
		{
			get { return m_MaintainDate; }
			set { m_IsChanged |= (m_MaintainDate != value); m_MaintainDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string MaintainUser
		{
			get { return m_MaintainUser; }
			set { m_IsChanged |= (m_MaintainUser != value); m_MaintainUser = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
