/***********************************************************
 ** File Name : BaseDataDepartment.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : AIC01/Kite.Zhang
 ** Create Date : 2011-08-10
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class BaseDataDepartment
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private int m_Id; 
		private int m_ManagerId; 
		private string m_Name; 
		private int m_ParentId; 
		private string m_Description; 
		private DateTime m_CreateDate; 
		private string m_CreateUser; 
		private DateTime m_MaintainDate; 
		private string m_MaintainUser; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public BaseDataDepartment()
		{
			m_Id = 0; 
			m_ManagerId = 0; 
			m_Name = null; 
			m_ParentId = 0; 
			m_Description = null; 
			m_CreateDate = new DateTime(); 
			m_CreateUser = null; 
			m_MaintainDate = new DateTime(); 
			m_MaintainUser = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public int Id
		{
			get { return m_Id; }
			set { m_IsChanged |= (m_Id != value); m_Id = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int ManagerId
		{
			get { return m_ManagerId; }
			set { m_IsChanged |= (m_ManagerId != value); m_ManagerId = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Name
		{
			get { return m_Name; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Name", value, value.ToString());
				
				m_IsChanged |= (m_Name != value); m_Name = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int ParentId
		{
			get { return m_ParentId; }
			set { m_IsChanged |= (m_ParentId != value); m_ParentId = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Description
		{
			get { return m_Description; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Description", value, value.ToString());
				
				m_IsChanged |= (m_Description != value); m_Description = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return m_CreateUser; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());
				
				m_IsChanged |= (m_CreateUser != value); m_CreateUser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime MaintainDate
		{
			get { return m_MaintainDate; }
			set { m_IsChanged |= (m_MaintainDate != value); m_MaintainDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string MaintainUser
		{
			get { return m_MaintainUser; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for MaintainUser", value, value.ToString());
				
				m_IsChanged |= (m_MaintainUser != value); m_MaintainUser = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
