/***********************************************************
 ** File Name : BfCaseinfo.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : AIC01/Kite.Zhang
 ** Create Date : 2011-08-26
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class BfCaseinfo
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private int m_Caseid; 
		private short m_Projectid; 
		private string m_ProjectName; 
		private short m_Moduleid; 
		private string m_ModulePath; 
		private string m_CaseTitle; 
		private int m_CasePriority; 
		private string m_CaseType; 
		private string m_CaseStatus; 
		private string m_CaseMethod; 
		private string m_CasePlan; 
		private string m_CaseSteps; 
		private string m_OpenedBy; 
		private DateTime m_OpenedDate; 
		private string m_AssignedTo; 
		private DateTime m_AssignedDate; 
		private string m_LastEditedBy; 
		private DateTime m_LastEditedDate; 
		private string m_ModifiedBy; 
		private string m_ScriptedBy; 
		private string m_ScriptedDate; 
		private string m_ScriptStatus; 
		private string m_ScriptLocation; 
		private string m_MailTo; 
		private string m_MarkForDeletion; 
		private string m_Linkid; 
		private string m_Bugid; 
		private string m_Resultid; 
		private string m_CaseKeyword; 
		private string m_CustomField1; 
		private string m_CustomField2; 
		private string m_CustomField3; 
		private string m_IsDroped; 
		private int m_DisplayOrder; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public BfCaseinfo()
		{
			m_Caseid = 0; 
			m_Projectid = 0; 
			m_ProjectName = null; 
			m_Moduleid = 0; 
			m_ModulePath = null; 
			m_CaseTitle = null; 
			m_CasePriority = 0; 
			m_CaseType = null; 
			m_CaseStatus = null; 
			m_CaseMethod = null; 
			m_CasePlan = null; 
			m_CaseSteps = null; 
			m_OpenedBy = null; 
			m_OpenedDate = new DateTime(); 
			m_AssignedTo = null; 
			m_AssignedDate = new DateTime(); 
			m_LastEditedBy = null; 
			m_LastEditedDate = new DateTime(); 
			m_ModifiedBy = null; 
			m_ScriptedBy = null; 
			m_ScriptedDate = null; 
			m_ScriptStatus = null; 
			m_ScriptLocation = null; 
			m_MailTo = null; 
			m_MarkForDeletion = null; 
			m_Linkid = null; 
			m_Bugid = null; 
			m_Resultid = null; 
			m_CaseKeyword = null; 
			m_CustomField1 = null; 
			m_CustomField2 = null; 
			m_CustomField3 = null; 
			m_IsDroped = null; 
			m_DisplayOrder = 0; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public int Caseid
		{
			get { return m_Caseid; }
			set { m_IsChanged |= (m_Caseid != value); m_Caseid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public short Projectid
		{
			get { return m_Projectid; }
			set { m_IsChanged |= (m_Projectid != value); m_Projectid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ProjectName
		{
			get { return m_ProjectName; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for ProjectName", value, value.ToString());
				
				m_IsChanged |= (m_ProjectName != value); m_ProjectName = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public short Moduleid
		{
			get { return m_Moduleid; }
			set { m_IsChanged |= (m_Moduleid != value); m_Moduleid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ModulePath
		{
			get { return m_ModulePath; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for ModulePath", value, value.ToString());
				
				m_IsChanged |= (m_ModulePath != value); m_ModulePath = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CaseTitle
		{
			get { return m_CaseTitle; }
			set	
			{
				if( value!= null && value.Length > 150)
					throw new ArgumentOutOfRangeException("Invalid value for CaseTitle", value, value.ToString());
				
				m_IsChanged |= (m_CaseTitle != value); m_CaseTitle = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int CasePriority
		{
			get { return m_CasePriority; }
			set { m_IsChanged |= (m_CasePriority != value); m_CasePriority = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CaseType
		{
			get { return m_CaseType; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for CaseType", value, value.ToString());
				
				m_IsChanged |= (m_CaseType != value); m_CaseType = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CaseStatus
		{
			get { return m_CaseStatus; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for CaseStatus", value, value.ToString());
				
				m_IsChanged |= (m_CaseStatus != value); m_CaseStatus = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CaseMethod
		{
			get { return m_CaseMethod; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for CaseMethod", value, value.ToString());
				
				m_IsChanged |= (m_CaseMethod != value); m_CaseMethod = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CasePlan
		{
			get { return m_CasePlan; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for CasePlan", value, value.ToString());
				
				m_IsChanged |= (m_CasePlan != value); m_CasePlan = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CaseSteps
		{
			get { return m_CaseSteps; }
			set	
			{
				if( value!= null && value.Length > 0)
					throw new ArgumentOutOfRangeException("Invalid value for CaseSteps", value, value.ToString());
				
				m_IsChanged |= (m_CaseSteps != value); m_CaseSteps = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string OpenedBy
		{
			get { return m_OpenedBy; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for OpenedBy", value, value.ToString());
				
				m_IsChanged |= (m_OpenedBy != value); m_OpenedBy = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime OpenedDate
		{
			get { return m_OpenedDate; }
			set { m_IsChanged |= (m_OpenedDate != value); m_OpenedDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string AssignedTo
		{
			get { return m_AssignedTo; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for AssignedTo", value, value.ToString());
				
				m_IsChanged |= (m_AssignedTo != value); m_AssignedTo = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime AssignedDate
		{
			get { return m_AssignedDate; }
			set { m_IsChanged |= (m_AssignedDate != value); m_AssignedDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string LastEditedBy
		{
			get { return m_LastEditedBy; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for LastEditedBy", value, value.ToString());
				
				m_IsChanged |= (m_LastEditedBy != value); m_LastEditedBy = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime LastEditedDate
		{
			get { return m_LastEditedDate; }
			set { m_IsChanged |= (m_LastEditedDate != value); m_LastEditedDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ModifiedBy
		{
			get { return m_ModifiedBy; }
			set	
			{
				if( value!= null && value.Length > 0)
					throw new ArgumentOutOfRangeException("Invalid value for ModifiedBy", value, value.ToString());
				
				m_IsChanged |= (m_ModifiedBy != value); m_ModifiedBy = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ScriptedBy
		{
			get { return m_ScriptedBy; }
			set	
			{
				if( value!= null && value.Length > 30)
					throw new ArgumentOutOfRangeException("Invalid value for ScriptedBy", value, value.ToString());
				
				m_IsChanged |= (m_ScriptedBy != value); m_ScriptedBy = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ScriptedDate
		{
			get { return m_ScriptedDate; }
			set	
			{
				if( value!= null && value.Length > 10)
					throw new ArgumentOutOfRangeException("Invalid value for ScriptedDate", value, value.ToString());
				
				m_IsChanged |= (m_ScriptedDate != value); m_ScriptedDate = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ScriptStatus
		{
			get { return m_ScriptStatus; }
			set	
			{
				if( value!= null && value.Length > 20)
					throw new ArgumentOutOfRangeException("Invalid value for ScriptStatus", value, value.ToString());
				
				m_IsChanged |= (m_ScriptStatus != value); m_ScriptStatus = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ScriptLocation
		{
			get { return m_ScriptLocation; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for ScriptLocation", value, value.ToString());
				
				m_IsChanged |= (m_ScriptLocation != value); m_ScriptLocation = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string MailTo
		{
			get { return m_MailTo; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for MailTo", value, value.ToString());
				
				m_IsChanged |= (m_MailTo != value); m_MailTo = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string MarkForDeletion
		{
			get { return m_MarkForDeletion; }
			set	
			{
				if( value!= null && value.Length > 0)
					throw new ArgumentOutOfRangeException("Invalid value for MarkForDeletion", value, value.ToString());
				
				m_IsChanged |= (m_MarkForDeletion != value); m_MarkForDeletion = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Linkid
		{
			get { return m_Linkid; }
			set	
			{
				if( value!= null && value.Length > 240)
					throw new ArgumentOutOfRangeException("Invalid value for Linkid", value, value.ToString());
				
				m_IsChanged |= (m_Linkid != value); m_Linkid = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Bugid
		{
			get { return m_Bugid; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for Bugid", value, value.ToString());
				
				m_IsChanged |= (m_Bugid != value); m_Bugid = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Resultid
		{
			get { return m_Resultid; }
			set	
			{
				if( value!= null && value.Length > 0)
					throw new ArgumentOutOfRangeException("Invalid value for Resultid", value, value.ToString());
				
				m_IsChanged |= (m_Resultid != value); m_Resultid = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CaseKeyword
		{
			get { return m_CaseKeyword; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for CaseKeyword", value, value.ToString());
				
				m_IsChanged |= (m_CaseKeyword != value); m_CaseKeyword = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CustomField1
		{
			get { return m_CustomField1; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for CustomField1", value, value.ToString());
				
				m_IsChanged |= (m_CustomField1 != value); m_CustomField1 = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CustomField2
		{
			get { return m_CustomField2; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for CustomField2", value, value.ToString());
				
				m_IsChanged |= (m_CustomField2 != value); m_CustomField2 = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CustomField3
		{
			get { return m_CustomField3; }
			set	
			{
				if( value!= null && value.Length > 255)
					throw new ArgumentOutOfRangeException("Invalid value for CustomField3", value, value.ToString());
				
				m_IsChanged |= (m_CustomField3 != value); m_CustomField3 = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string IsDroped
		{
			get { return m_IsDroped; }
			set	
			{
				if( value!= null && value.Length > 0)
					throw new ArgumentOutOfRangeException("Invalid value for IsDroped", value, value.ToString());
				
				m_IsChanged |= (m_IsDroped != value); m_IsDroped = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int DisplayOrder
		{
			get { return m_DisplayOrder; }
			set { m_IsChanged |= (m_DisplayOrder != value); m_DisplayOrder = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
