/***********************************************************
 ** File Name : CRComments.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : Tim
 ** Create Date : 2012-09-29
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
    [Serializable]
    public sealed class CRComments
    {
        #region Private Members
        private bool m_IsChanged;
        private bool m_IsDeleted;
        private string m_PMSID;
        private string m_CRID;
        private string m_PMComments;
        private string m_SDComments;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public CRComments()
        {
            m_PMSID = null;
            m_CRID = null;
            m_PMComments = " ";
            m_SDComments = " ";
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties
        public string PMSID
        {
            get { return m_PMSID; }
            set { m_IsChanged |= (m_PMSID != value); m_PMSID = value; }
        }

        public string CRID
        {
            get { return m_CRID; }
            set { m_IsChanged |= (m_CRID != value); m_CRID = value; }
        }
        public string PMComments
        {
            get { return m_PMComments; }
            set { m_IsChanged |= (m_PMComments != value); m_PMComments = value; }
        }

        public string SDComments
        {
            get { return m_SDComments; }
            set { m_IsChanged |= (m_SDComments != value); m_SDComments = value; }
        }
        
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return m_IsChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return m_IsDeleted; }
        }

        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            m_IsDeleted = true;
            m_IsChanged = true;
        }

        #endregion


    }
}
