/***********************************************************
 ** File Name : ItarmCrList.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-20
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class ItarmCrList
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private int m_Serial; 
		private string m_CrId; 
		private string m_CrName; 
		private string m_Site; 
		private string m_Creator; 
		private DateTime m_CreateDate;
	    private string m_Pm;
	    private string m_System;

	    private string m_Sd;
	    private string m_PmsId;
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public ItarmCrList()
		{
			m_Serial = 0; 
			m_CrId = null; 
			m_CrName = null; 
			m_Site = null; 
			m_Creator = null; 
			m_CreateDate = new DateTime();
		    m_Pm = null;
		    m_System = null;
		    m_Sd = null;
		    m_PmsId = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
        /// <summary>
        /// 
        /// </summary>		
        public string Sd
        {
            get { return m_Sd; }
            set { m_IsChanged |= (m_Sd != value); m_Sd = value; }
        }


        /// <summary>
        /// 
        /// </summary>		
        public string PmsId
        {
            get { return m_PmsId; }
            set { m_IsChanged |= (m_PmsId != value); m_PmsId = value; }
        }



		/// <summary>
		/// 
		/// </summary>		
		public int Serial
		{
			get { return m_Serial; }
			set { m_IsChanged |= (m_Serial != value); m_Serial = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CrId
		{
			get { return m_CrId; }
			set { m_IsChanged |= (m_CrId != value); m_CrId = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CrName
		{
			get { return m_CrName; }
			set { m_IsChanged |= (m_CrName != value); m_CrName = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Site
		{
			get { return m_Site; }
			set { m_IsChanged |= (m_Site != value); m_Site = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Creator
		{
			get { return m_Creator; }
			set { m_IsChanged |= (m_Creator != value); m_Creator = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}

        /// <summary>
        /// 
        /// </summary>		
        public string Pm
        {
            get { return m_Pm; }
            set { m_IsChanged |= (m_Pm != value); m_Pm = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string System
        {
            get { return m_System; }
            set { m_IsChanged |= (m_System != value); m_System = value; }
        }
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
