/***********************************************************
 ** File Name : PmsChangeHistory.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-18
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PmsChangeHistory
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private string m_PmsId; 
		private string m_ChangeContent; 
		private string m_Action; 
		private string m_Creator; 
		private DateTime m_CreateDate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PmsChangeHistory()
		{
            m_PmsId = null; 
			m_ChangeContent =null;
            m_Action = null;
            m_Creator = null;  
			m_CreateDate = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public string PmsId
		{
			get { return m_PmsId; }
			set { m_IsChanged |= (m_PmsId != value); m_PmsId = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string ChangeContent
		{
			get { return m_ChangeContent; }
			set { m_IsChanged |= (m_ChangeContent != value); m_ChangeContent = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Action
		{
			get { return m_Action; }
			set { m_IsChanged |= (m_Action != value); m_Action = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Creator
		{
			get { return m_Creator; }
			set { m_IsChanged |= (m_Creator != value); m_Creator = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
