/***********************************************************
 ** File Name : PmsDocuments.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-17
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PmsDocuments
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private string m_PmsId; 
		private int m_DocTypeId;
        private string m_FileName;
        private string m_Path;
        private string m_Size;
        private string m_Creator; 
		private DateTime m_CreateDate;
        private string m_TypeName; 
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PmsDocuments()
		{
			m_PmsId = null; 
			m_DocTypeId = 0; 
			m_FileName = null; 
			m_Path = null; 
			m_Size = null; 
			m_Creator = null; 
			m_CreateDate = new DateTime();
            m_TypeName = null;
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public string PmsId
		{
			get { return m_PmsId; }
			set { m_IsChanged |= (m_PmsId != value); m_PmsId = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int DocTypeId
		{
			get { return m_DocTypeId; }
			set { m_IsChanged |= (m_DocTypeId != value); m_DocTypeId = value; }
		}

        public string TypeName
        {
            get { return m_TypeName; }
            set { m_IsChanged |= (m_TypeName != value); m_TypeName = value; }
        }
			
		/// <summary>
		/// 
		/// </summary>		
		public string FileName
		{
			get { return m_FileName; }
			set { m_IsChanged |= (m_FileName != value); m_FileName = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Path
		{
			get { return m_Path; }
			set { m_IsChanged |= (m_Path != value); m_Path = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Size
		{
			get { return m_Size; }
			set { m_IsChanged |= (m_Size != value); m_Size = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Creator
		{
			get { return m_Creator; }
			set { m_IsChanged |= (m_Creator != value); m_Creator = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
