/***********************************************************
 ** File Name : PmsHead.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-12
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;


namespace Qisda.PMS.Entity
{
    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class PmsHead
    {
        #region Private Members
        private bool m_IsChanged;
        private bool m_IsDeleted;
        private string m_Vid;
        private string m_PmsId;
        private string m_PmsName;
        private string m_Type;
        private string m_Description;
        private string m_ResolveDescription;
        private string m_System;
        private string m_Domain;
        private string m_Priority;
        private string m_Site;
        private string m_ImpactSite;
        private string m_NewVersion;
        private string m_OldVersion;
        private DateTime m_DueDate;
        private DateTime m_PlanStartDate;
        private DateTime m_ActualStartDate;
        private DateTime m_ReleaseDate;
        private DateTime m_CloseDate;
        private DateTime m_SDPConfirmDate;
        
        private int m_Stage;
        private string m_Pm;
        private string m_Sd;
        private string m_Se;
        private string m_Qa;
        private int m_AbnormalStage;
        private string m_Rerver1;
        private string m_Rerver2;
        private string m_Rerver3;
        private string m_Rerver4;
        private string m_Rerver5;
        private DateTime m_CreateDate;
        private string m_Creator;
        private DateTime m_MaintainDate;
        private string m_MaintainUser;
        private string m_NeedSTP;
        private string m_NeedSTC;
        private string m_Category;
        private string m_CodeReview;
        private string m_SelfTesting;
        private string m_OwnerDept;
        private string m_RelatedCrNo;

        private string m_CrId;
        private DateTime m_CreateDateFrom;
        private DateTime m_CreateDateTo;
        private DateTime m_ReleaseDateFrom;
        private DateTime m_ReleaseDateTo;
        private DateTime m_DueDateFrom;
        private DateTime m_DueDateTo;
        private string m_StageName;
        private string m_UserName;
        private string m_NoStageName;
        private string m_Progress;
        private string m_TotalManpower;

        private string m_BugFreeProject;
        private string m_BugFreeModule;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public PmsHead()
        {
            m_Vid = null;
            m_PmsId = null;
            m_PmsName = null;
            m_Type = null;
            m_Description = null;
            m_ResolveDescription = null;
            m_System = null;
            m_Domain = null;
            m_Priority = null;
            m_Site = null;
            m_ImpactSite = null;
            m_NewVersion = null;
            m_OldVersion = null;
            m_DueDate = new DateTime();
            m_PlanStartDate = new DateTime();
            m_ActualStartDate = new DateTime();
            m_ReleaseDate = new DateTime();
            m_CloseDate = new DateTime();
            m_Stage = 0;
            m_Pm = null;
            m_Sd = null;
            m_Se = null;
            m_Qa = null;
            m_AbnormalStage = 0;
            m_Rerver1 = null;
            m_Rerver2 = null;
            m_Rerver3 = null;
            m_Rerver4 = null;
            m_Rerver5 = null;
            m_CreateDate = new DateTime();
            m_Creator = null;
            m_MaintainDate = new DateTime();
            m_MaintainUser = null;
            m_NeedSTP = null;
            m_NeedSTC = null;
            m_Category = null;
            m_CodeReview = null;
            m_SelfTesting = null;
            m_OwnerDept = null;
            m_RelatedCrNo = null;

            m_CrId = null;
            m_CreateDateFrom = new DateTime();
            m_CreateDateTo = new DateTime();
            m_ReleaseDateFrom = new DateTime();
            m_ReleaseDateTo = new DateTime();
            m_DueDateFrom = new DateTime();
            m_DueDateTo = new DateTime();
            m_StageName = null;
            m_NoStageName = null;
            m_UserName = null;
            m_Progress = null;
            m_TotalManpower = null;

            m_BugFreeProject = null;
            m_BugFreeModule = null;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		
        public string Vid
        {
            get { return m_Vid; }
            set { m_IsChanged |= (m_Vid != value); m_Vid = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string PmsId
        {
            get { return m_PmsId; }
            set { m_IsChanged |= (m_PmsId != value); m_PmsId = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string PmsName
        {
            get { return m_PmsName; }
            set { m_IsChanged |= (m_PmsName != value); m_PmsName = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Type
        {
            get { return m_Type; }
            set { m_IsChanged |= (m_Type != value); m_Type = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Description
        {
            get { return m_Description; }
            set { m_IsChanged |= (m_Description != value); m_Description = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ResolveDescription
        {
            get { return m_ResolveDescription; }
            set { m_IsChanged |= (m_ResolveDescription != value); m_ResolveDescription = value; }
        }
        /// <summary>
        /// 
        /// </summary>		
        public string System
        {
            get { return m_System; }
            set { m_IsChanged |= (m_System != value); m_System = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Domain
        {
            get { return m_Domain; }
            set { m_IsChanged |= (m_Domain != value); m_Domain = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Priority
        {
            get { return m_Priority; }
            set { m_IsChanged |= (m_Priority != value); m_Priority = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Site
        {
            get { return m_Site; }
            set { m_IsChanged |= (m_Site != value); m_Site = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ImpactSite
        {
            get { return m_ImpactSite; }
            set { m_IsChanged |= (m_ImpactSite != value); m_ImpactSite = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string NewVersion
        {
            get { return m_NewVersion; }
            set { m_IsChanged |= (m_NewVersion != value); m_NewVersion = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string OldVersion
        {
            get { return m_OldVersion; }
            set { m_IsChanged |= (m_OldVersion != value); m_OldVersion = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime DueDate
        {
            get { return m_DueDate; }
            set { m_IsChanged |= (m_DueDate != value); m_DueDate = value; }
        }

        
        /// <summary>
        /// 
        /// </summary>		
        public DateTime PlanStartDate
        {
            get { return m_PlanStartDate; }
            set { m_IsChanged |= (m_PlanStartDate != value); m_PlanStartDate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime ActualStartDate
        {
            get { return m_ActualStartDate; }
            set { m_IsChanged |= (m_ActualStartDate != value); m_ActualStartDate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime ReleaseDate
        {
            get { return m_ReleaseDate; }
            set { m_IsChanged |= (m_ReleaseDate != value); m_ReleaseDate = value; }
        }

        public DateTime ReleaseDateFrom
        {
            get { return m_ReleaseDateFrom; }
            set { m_IsChanged |= (m_ReleaseDateFrom != value); m_ReleaseDateFrom = value; }
        }

        public DateTime ReleaseDateTo
        {
            get { return m_ReleaseDateTo; }
            set { m_IsChanged |= (m_ReleaseDateTo != value); m_ReleaseDateTo = value; }
        }

        public DateTime DueDateFrom
        {
            get { return m_DueDateFrom; }
            set { m_IsChanged |= (m_DueDateFrom != value); m_DueDateFrom = value; }
        }

        public DateTime DueDateTo
        {
            get { return m_DueDateTo; }
            set { m_IsChanged |= (m_DueDateTo != value); m_DueDateTo = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime CloseDate
        {
            get { return m_CloseDate; }
            set { m_IsChanged |= (m_CloseDate != value); m_CloseDate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime SDPConfirmDate
        {
            get { return m_SDPConfirmDate; }
            set { m_IsChanged |= (m_SDPConfirmDate != value); m_SDPConfirmDate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int Stage
        {
            get { return m_Stage; }
            set { m_IsChanged |= (m_Stage != value); m_Stage = value; }
        }

        public string StageName
        {
            get { return m_StageName; }
            set { m_IsChanged |= (m_StageName != value); m_StageName = value; }
        }

        public string NoStageName
        {
            get { return m_NoStageName; }
            set { m_IsChanged |= (m_NoStageName != value); m_NoStageName = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Pm
        {
            get { return m_Pm; }
            set { m_IsChanged |= (m_Pm != value); m_Pm = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Sd
        {
            get { return m_Sd; }
            set { m_IsChanged |= (m_Sd != value); m_Sd = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Se
        {
            get { return m_Se; }
            set { m_IsChanged |= (m_Se != value); m_Se = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Qa
        {
            get { return m_Qa; }
            set { m_IsChanged |= (m_Qa != value); m_Qa = value; }
        }

        public string UserName
        {
            get { return m_UserName; }
            set { m_IsChanged |= (m_UserName != value); m_UserName = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public int AbnormalStage
        {
            get { return m_AbnormalStage; }
            set { m_IsChanged |= (m_AbnormalStage != value); m_AbnormalStage = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Rerver1
        {
            get { return m_Rerver1; }
            set { m_IsChanged |= (m_Rerver1 != value); m_Rerver1 = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Rerver2
        {
            get { return m_Rerver2; }
            set { m_IsChanged |= (m_Rerver2 != value); m_Rerver2 = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Rerver3
        {
            get { return m_Rerver3; }
            set { m_IsChanged |= (m_Rerver3 != value); m_Rerver3 = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Rerver4
        {
            get { return m_Rerver4; }
            set { m_IsChanged |= (m_Rerver4 != value); m_Rerver4 = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Rerver5
        {
            get { return m_Rerver5; }
            set { m_IsChanged |= (m_Rerver5 != value); m_Rerver5 = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime CreateDate
        {
            get { return m_CreateDate; }
            set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
        }

        public DateTime CreateDateFrom
        {
            get { return m_CreateDateFrom; }
            set { m_IsChanged |= (m_CreateDateFrom != value); m_CreateDateFrom = value; }
        }

        public DateTime CreateDateTo
        {
            get { return m_CreateDateTo; }
            set { m_IsChanged |= (m_CreateDateTo != value); m_CreateDateTo = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Creator
        {
            get { return m_Creator; }
            set { m_IsChanged |= (m_Creator != value); m_Creator = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime MaintainDate
        {
            get { return m_MaintainDate; }
            set { m_IsChanged |= (m_MaintainDate != value); m_MaintainDate = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string MaintainUser
        {
            get { return m_MaintainUser; }
            set { m_IsChanged |= (m_MaintainUser != value); m_MaintainUser = value; }
        }

        public string NeedSTP
        {
            get { return m_NeedSTP; }
            set { m_IsChanged |= (m_NeedSTP != value); m_NeedSTP = value; }
        }
        public string NeedSTC
        {
            get { return m_NeedSTC; }
            set { m_IsChanged |= (m_NeedSTC != value); m_NeedSTC = value; }
        }
        public string Category
        {
            get { return m_Category; }
            set { m_IsChanged |= (m_Category != value); m_Category = value; }
        }
        public string CodeReview
        {
            get { return m_CodeReview; }
            set { m_IsChanged |= (m_CodeReview != value); m_CodeReview = value; }
        }
        public string SelfTesting
        {
            get { return m_SelfTesting; }
            set { m_IsChanged |= (m_SelfTesting != value); m_SelfTesting = value; }
        }
        public string OwnerDept
        {
            get { return m_OwnerDept; }
            set { m_IsChanged |= (m_OwnerDept != value); m_OwnerDept = value; }
        }


        public string RelatedCrNo
        {
            get { return m_RelatedCrNo; }
            set { m_IsChanged |= (m_RelatedCrNo != value); m_RelatedCrNo = value; }

        }

        public string TotalManpower
        {
            get { return m_TotalManpower; }
            set { m_IsChanged |= (m_TotalManpower != value); m_TotalManpower = value; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return m_IsChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return m_IsDeleted; }
        }

        public string CrId
        {
            get { return m_CrId; }
            set { m_IsChanged |= (m_CrId != value); m_CrId = value; }
        }

        public string Progress
        {
            get { return m_Progress; }
            set { m_IsChanged |= (m_Progress != value); m_Progress = value; }
        }

        public string BugFreeProject
        {
            get { return m_BugFreeProject; }
            set { m_IsChanged |= (m_BugFreeProject != value); m_BugFreeProject = value; }
        }

        public string BugFreeModule
        {
            get { return m_BugFreeModule; }
            set { m_IsChanged |= (m_BugFreeModule != value); m_BugFreeModule = value; }
        }
        #endregion


        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            m_IsDeleted = true;
            m_IsChanged = true;
        }

        #endregion


    }
}
