/***********************************************************
 ** File Name : PmsSdpRefcost.cs
 ** Copyright (C) 2014 Qisda Corporation. All rights reserved.
 **
 ** Creator : AIC01/ITO.Abel.Li
 ** Create Date : 2014-01-17
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PmsSdpRefcost
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private string m_Vid; 
		private int m_OperationType; 
		private int m_Tasktype; 
		private int m_Functiontype; 
		private int m_TaskComplexity; 
		private int m_Programlanguage; 
		private float m_Refcost; 
		private DateTime m_CreateDate; 
		private string m_Creator; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PmsSdpRefcost()
		{
			m_Vid = null; 
			m_OperationType = 0; 
			m_Tasktype = 0; 
			m_Functiontype = 0; 
			m_TaskComplexity = 0; 
			m_Programlanguage = 0; 
			m_Refcost = 0; 
			m_CreateDate = new DateTime(); 
			m_Creator = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 有效位
		/// </summary>		
		public string Vid
		{
			get { return m_Vid; }
			set	
			{
				if( value!= null && value.Length > 2)
					throw new ArgumentOutOfRangeException("Invalid value for Vid", value, value.ToString());
				
				m_IsChanged |= (m_Vid != value); m_Vid = value;
			}
		}
			
		/// <summary>
		/// 作业方式
		/// </summary>		
		public int OperationType
		{
			get { return m_OperationType; }
			set { m_IsChanged |= (m_OperationType != value); m_OperationType = value; }
		}
			
		/// <summary>
		/// 任务类型
		/// </summary>		
		public int Tasktype
		{
			get { return m_Tasktype; }
			set { m_IsChanged |= (m_Tasktype != value); m_Tasktype = value; }
		}
			
		/// <summary>
		/// 功能分类
		/// </summary>		
		public int Functiontype
		{
			get { return m_Functiontype; }
			set { m_IsChanged |= (m_Functiontype != value); m_Functiontype = value; }
		}
			
		/// <summary>
		/// 任务复杂度
		/// </summary>		
		public int TaskComplexity
		{
			get { return m_TaskComplexity; }
			set { m_IsChanged |= (m_TaskComplexity != value); m_TaskComplexity = value; }
		}
			
		/// <summary>
		/// 编程语言
		/// </summary>		
		public int Programlanguage
		{
			get { return m_Programlanguage; }
			set { m_IsChanged |= (m_Programlanguage != value); m_Programlanguage = value; }
		}
			
		/// <summary>
		/// 参考工时
		/// </summary>		
		public float Refcost
		{
			get { return m_Refcost; }
			set { m_IsChanged |= (m_Refcost != value); m_Refcost = value; }
		}
			
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// 创建人
		/// </summary>		
		public string Creator
		{
			get { return m_Creator; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Creator", value, value.ToString());
				
				m_IsChanged |= (m_Creator != value); m_Creator = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
