/***********************************************************
 ** File Name : PmsStage.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-12
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PmsStage
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private string  m_Vid;
        private int m_StageId;
        private string m_StageName;
        private string m_StageFlag;
        private string m_Creator; 
		private DateTime m_CreateDate; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PmsStage()
		{
			m_Vid = null ; 
			m_StageId = 0;
            m_StageName = null;
            m_StageFlag = null;
            m_Creator = null;
            m_CreateDate = new DateTime(); 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public string Vid
		{
			get { return m_Vid; }
			set { m_IsChanged |= (m_Vid != value); m_Vid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int StageId
		{
			get { return m_StageId; }
			set { m_IsChanged |= (m_StageId != value); m_StageId = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string StageName
		{
			get { return m_StageName; }
			set { m_IsChanged |= (m_StageName != value); m_StageName = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string StageFlag
		{
			get { return m_StageFlag; }
			set { m_IsChanged |= (m_StageFlag != value); m_StageFlag = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Creator
		{
			get { return m_Creator; }
			set { m_IsChanged |= (m_Creator != value); m_Creator = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
