/***********************************************************
 ** File Name : PmsSdpVersion.cs
 ** Copyright (C) 2014 Qisda Corporation. All rights reserved.
 **
 ** Creator : AIC01/Ename.Wang
 ** Create Date : 2014-01-24
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class PmsSdpVersion
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private int m_Serial; 
		private int m_Taskno; 
		private string m_Pmsid; 
		private DateTime m_PlanStartDay; 
		private DateTime m_PlanEndDay; 
		private float m_PlanCost; 
		private float m_RefCost; 
		private float m_Version; 
		private DateTime m_CreateDate; 
		private string m_Creator; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public PmsSdpVersion()
		{
			m_Serial = 0; 
			m_Taskno = 0; 
			m_Pmsid = null; 
			m_PlanStartDay = new DateTime(); 
			m_PlanEndDay = new DateTime(); 
			m_PlanCost = 0; 
			m_RefCost = 0; 
			m_Version = 0; 
			m_CreateDate = new DateTime(); 
			m_Creator = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 自增栏位
		/// </summary>		
		public int Serial
		{
			get { return m_Serial; }
			set { m_IsChanged |= (m_Serial != value); m_Serial = value; }
		}
			
		/// <summary>
		/// 任务编号
		/// </summary>		
		public int Taskno
		{
			get { return m_Taskno; }
			set { m_IsChanged |= (m_Taskno != value); m_Taskno = value; }
		}
			
		/// <summary>
		/// PMS ID
		/// </summary>		
		public string Pmsid
		{
			get { return m_Pmsid; }
			set	
			{
				if( value!= null && value.Length > 15)
					throw new ArgumentOutOfRangeException("Invalid value for Pmsid", value, value.ToString());
				
				m_IsChanged |= (m_Pmsid != value); m_Pmsid = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime PlanStartDay
		{
			get { return m_PlanStartDay; }
			set { m_IsChanged |= (m_PlanStartDay != value); m_PlanStartDay = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime PlanEndDay
		{
			get { return m_PlanEndDay; }
			set { m_IsChanged |= (m_PlanEndDay != value); m_PlanEndDay = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public float PlanCost
		{
			get { return m_PlanCost; }
			set { m_IsChanged |= (m_PlanCost != value); m_PlanCost = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public float RefCost
		{
			get { return m_RefCost; }
			set { m_IsChanged |= (m_RefCost != value); m_RefCost = value; }
		}
			
		/// <summary>
		/// SDP的版本
		/// </summary>		
		public float Version
		{
			get { return m_Version; }
			set { m_IsChanged |= (m_Version != value); m_Version = value; }
		}
			
		/// <summary>
		/// 创建时间
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// 创建人
		/// </summary>		
		public string Creator
		{
			get { return m_Creator; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for Creator", value, value.ToString());
				
				m_IsChanged |= (m_Creator != value); m_Creator = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
