/***********************************************************
 ** File Name : SdpDetailTemplate.cs
 ** Copyright (C) 2011 Qisda Corporation. All rights reserved.
 **
 ** Creator : HI1/CJ.Chen
 ** Create Date : 2011-01-18
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class SdpDetailTemplate
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private string m_Pmsid;
        private int m_Taskno; 
		private string m_TaskName; 
		private double m_Plancost;
        private double m_Actualcost; 
		private DateTime m_Planstartday;
        private DateTime m_Planendday;
        private DateTime m_Actualstartday;
        private DateTime m_Actualendday;
        private int m_PretaskNo; 
		private string m_Role;
        private string m_Resource;
        private string m_Remark;
        private int m_Type;
        private string m_Iseditable;
        private string m_Deleteflag;
        private DateTime m_Createdate;
        private string m_Createuser;
        private DateTime m_Maintaindate;
        private string m_Maintainuser;
        private string m_Phase;
        private string m_Extension; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public SdpDetailTemplate()
		{
			m_Pmsid = null;
            m_Taskno = 0; 
			m_TaskName = null; 
			m_Plancost = 0; 
			m_Actualcost = 0;
            m_Planstartday = new DateTime();
            m_Planendday = new DateTime();
            m_Actualstartday = new DateTime();
            m_Actualendday = new DateTime();
            m_PretaskNo = 0;
            m_Role = null;
            m_Resource = null;
            m_Remark = null; 
            m_Type = 0;
            m_Iseditable = null; 
            m_Deleteflag = null;
            m_Createdate = new DateTime();
            m_Createuser = null;
            m_Maintaindate = new DateTime();
            m_Maintainuser = null; 
            m_Phase = null; 
            m_Extension = null;  
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public string Pmsid
		{
			get { return m_Pmsid; }
			set { m_IsChanged |= (m_Pmsid != value); m_Pmsid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public int Taskno
		{
			get { return m_Taskno; }
			set { m_IsChanged |= (m_Taskno != value); m_Taskno = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string TaskName
		{
			get { return m_TaskName; }
			set { m_IsChanged |= (m_TaskName != value); m_TaskName = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public double Plancost
		{
			get { return m_Plancost; }
			set { m_IsChanged |= (m_Plancost != value); m_Plancost = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public double Actualcost
		{
			get { return m_Actualcost; }
			set { m_IsChanged |= (m_Actualcost != value); m_Actualcost = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime Planstartday
		{
			get { return m_Planstartday; }
			set { m_IsChanged |= (m_Planstartday != value); m_Planstartday = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public DateTime Planendday
		{
			get { return m_Planendday; }
			set { m_IsChanged |= (m_Planendday != value); m_Planendday = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public DateTime Actualstartday
		{
			get { return m_Actualstartday; }
			set { m_IsChanged |= (m_Actualstartday != value); m_Actualstartday = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public DateTime Actualendday
		{
			get { return m_Actualendday; }
			set { m_IsChanged |= (m_Actualendday != value); m_Actualendday = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public int PretaskNo
		{
			get { return m_PretaskNo; }
			set { m_IsChanged |= (m_PretaskNo != value); m_PretaskNo = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Role
		{
			get { return m_Role; }
			set { m_IsChanged |= (m_Role != value); m_Role = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Resource
		{
			get { return m_Resource; }
			set { m_IsChanged |= (m_Resource != value); m_Resource = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Remark
		{
			get { return m_Remark; }
			set { m_IsChanged |= (m_Remark != value); m_Remark = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public int Type
		{
			get { return m_Type; }
			set { m_IsChanged |= (m_Type != value); m_Type = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Iseditable
		{
			get { return m_Iseditable; }
			set { m_IsChanged |= (m_Iseditable != value); m_Iseditable = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Deleteflag
		{
			get { return m_Deleteflag; }
			set { m_IsChanged |= (m_Deleteflag != value); m_Deleteflag = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime Createdate
		{
			get { return m_Createdate; }
			set { m_IsChanged |= (m_Createdate != value); m_Createdate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Createuser
		{
			get { return m_Createuser; }
			set { m_IsChanged |= (m_Createuser != value); m_Createuser = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public DateTime Maintaindate
		{
			get { return m_Maintaindate; }
			set { m_IsChanged |= (m_Maintaindate != value); m_Maintaindate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
        public string Maintainuser
		{
			get { return m_Maintainuser; }
			set { m_IsChanged |= (m_Maintainuser != value); m_Maintainuser = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Phase
		{
			get { return m_Phase; }
			set { m_IsChanged |= (m_Phase != value); m_Phase = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Extension
		{
			get { return m_Extension; }
			set { m_IsChanged |= (m_Extension != value); m_Extension = value; }
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
