/***********************************************************
 ** File Name : TfsTeam.cs
 ** Copyright (C) 2013 Qisda Corporation. All rights reserved.
 **
 ** Creator : AIC01/Justin.Meng
 ** Create Date : 2013-12-28
 ** Modifier :
 ** Modify Date :
 **
 ** Description:
 **
 ***********************************************************/
using System;

namespace Qisda.PMS.Entity
{
	/// <summary>
	///	Generated by MyGeneration using the IBatis Object Mapping template
	/// </summary>
	[Serializable]
	public sealed class TfsTeam
	{
		#region Private Members
		private bool m_IsChanged;
		private bool m_IsDeleted;
		private int m_Teamid; 
		private string m_TeamName; 
		private int m_TeamLeaderid; 
		private string m_Description; 
		private DateTime m_CreateDate; 
		private string m_CreateUser; 
		private DateTime m_MaintainDate; 
		private string m_MaintainUser; 		
		#endregion
		
		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public TfsTeam()
		{
			m_Teamid = 0; 
			m_TeamName = null; 
			m_TeamLeaderid = 0; 
			m_Description = null; 
			m_CreateDate = new DateTime(); 
			m_CreateUser = null; 
			m_MaintainDate = new DateTime(); 
			m_MaintainUser = null; 
		}
		#endregion // End of Default ( Empty ) Class Constuctor
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public int Teamid
		{
			get { return m_Teamid; }
			set { m_IsChanged |= (m_Teamid != value); m_Teamid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string TeamName
		{
			get { return m_TeamName; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for TeamName", value, value.ToString());
				
				m_IsChanged |= (m_TeamName != value); m_TeamName = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public int TeamLeaderid
		{
			get { return m_TeamLeaderid; }
			set { m_IsChanged |= (m_TeamLeaderid != value); m_TeamLeaderid = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string Description
		{
			get { return m_Description; }
			set	
			{
				if( value!= null && value.Length > 100)
					throw new ArgumentOutOfRangeException("Invalid value for Description", value, value.ToString());
				
				m_IsChanged |= (m_Description != value); m_Description = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime CreateDate
		{
			get { return m_CreateDate; }
			set { m_IsChanged |= (m_CreateDate != value); m_CreateDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string CreateUser
		{
			get { return m_CreateUser; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for CreateUser", value, value.ToString());
				
				m_IsChanged |= (m_CreateUser != value); m_CreateUser = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public DateTime MaintainDate
		{
			get { return m_MaintainDate; }
			set { m_IsChanged |= (m_MaintainDate != value); m_MaintainDate = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public string MaintainUser
		{
			get { return m_MaintainUser; }
			set	
			{
				if( value!= null && value.Length > 50)
					throw new ArgumentOutOfRangeException("Invalid value for MaintainUser", value, value.ToString());
				
				m_IsChanged |= (m_MaintainUser != value); m_MaintainUser = value;
			}
		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return m_IsChanged; }
		}
		
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsDeleted
		{
			get { return m_IsDeleted; }
		}
		
		#endregion 
		
		
		#region Public Functions
		
		/// <summary>
		/// mark the item as deleted
		/// </summary>
		public void MarkAsDeleted()
		{
			m_IsDeleted = true;
			m_IsChanged = true;
		}
		
		#endregion
		
		
	}
}
