//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureRes_Message_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureRes_Message_EN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CultureRes_Message_EN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to add new. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_ADD {
            get {
                return ResourceManager.GetString("MSG_ERR_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please check your user name and password, try again. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_CHECK_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_ERR_CHECK_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to delete. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to delete the form in FlowER! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_FLOWER_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to send the form to FlowER. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_FLOWER_SEND_FAIL {
            get {
                return ResourceManager.GetString("MSG_ERR_FLOWER_SEND_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to log the action to file! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_LOG {
            get {
                return ResourceManager.GetString("MSG_ERR_LOG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail service configuration is incorrect! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_MAIL_CONN_SEND {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_CONN_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to create template file for mail service! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_MAIL_TEMPLATE {
            get {
                return ResourceManager.GetString("MSG_ERR_MAIL_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password can not be empty value. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Incorrect password. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_PASSWORD_INCORRECT {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to retrieve your password. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_PASSWORD_RTV {
            get {
                return ResourceManager.GetString("MSG_ERR_PASSWORD_RTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This setting has already existed in the database. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_SETTING_EXIST {
            get {
                return ResourceManager.GetString("MSG_ERR_SETTING_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The SMS switch is off, you can not send short message! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_SMS_SIWTCH_OFF {
            get {
                return ResourceManager.GetString("MSG_ERR_SMS_SIWTCH_OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to update. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_UPDATE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to upload a file! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_UPLOAD {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not locate the file path. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_UPLOAD_LACATE {
            get {
                return ResourceManager.GetString("MSG_ERR_UPLOAD_LACATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to delete User account. \nDescription:  的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_USER_DELETE {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User name can not be empty value. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_USER_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_USER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The parameters can not be empty value! 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_VALUE_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ERR_VALUE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error trying to analyze the XML package. 的本地化字符串。
        /// </summary>
        internal static string MSG_ERR_XML_FORMAT {
            get {
                return ResourceManager.GetString("MSG_ERR_XML_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete the selected item(s)? 的本地化字符串。
        /// </summary>
        internal static string MSG_TIP_DELETE_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_TIP_DELETE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your password has been sent to your mailbox. 的本地化字符串。
        /// </summary>
        internal static string MSG_TIP_PASSWORD_MAIL {
            get {
                return ResourceManager.GetString("MSG_TIP_PASSWORD_MAIL", resourceCulture);
            }
        }
    }
}
