//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureRes_Caption_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureRes_Caption_EN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CultureRes_Caption_EN", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Add 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_ADD {
            get {
                return ResourceManager.GetString("CAP_BTN_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_CLOSE {
            get {
                return ResourceManager.GetString("CAP_BTN_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_COLLAPSE {
            get {
                return ResourceManager.GetString("CAP_BTN_COLLAPSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_DELETE {
            get {
                return ResourceManager.GetString("CAP_BTN_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_EXPAND {
            get {
                return ResourceManager.GetString("CAP_BTN_EXPAND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forget Password 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_GETPASSWORD {
            get {
                return ResourceManager.GetString("CAP_BTN_GETPASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_LOGIN {
            get {
                return ResourceManager.GetString("CAP_BTN_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_OK {
            get {
                return ResourceManager.GetString("CAP_BTN_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_QUERY {
            get {
                return ResourceManager.GetString("CAP_BTN_QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Query all 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_QUERYALL {
            get {
                return ResourceManager.GetString("CAP_BTN_QUERYALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_REFRESH {
            get {
                return ResourceManager.GetString("CAP_BTN_REFRESH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repaire 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_REPAIRE {
            get {
                return ResourceManager.GetString("CAP_BTN_REPAIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_SAVE {
            get {
                return ResourceManager.GetString("CAP_BTN_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Upload 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_UPLOAD {
            get {
                return ResourceManager.GetString("CAP_BTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validate 的本地化字符串。
        /// </summary>
        internal static string CAP_BTN_VALIDATE {
            get {
                return ResourceManager.GetString("CAP_BTN_VALIDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Address 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_ADDRESS {
            get {
                return ResourceManager.GetString("CAP_LBL_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Department 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_DEPT {
            get {
                return ResourceManager.GetString("CAP_LBL_DEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_DESC {
            get {
                return ResourceManager.GetString("CAP_LBL_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display style 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_DISP_STYLE {
            get {
                return ResourceManager.GetString("CAP_LBL_DISP_STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_PASSWORD {
            get {
                return ResourceManager.GetString("CAP_LBL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Result 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_RESULT {
            get {
                return ResourceManager.GetString("CAP_LBL_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_ROLE {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role ID 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_ROLE_ID {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Name 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_ROLE_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_ROLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_USER {
            get {
                return ResourceManager.GetString("CAP_LBL_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Name 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_USER_NAME {
            get {
                return ResourceManager.GetString("CAP_LBL_USER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value 的本地化字符串。
        /// </summary>
        internal static string CAP_LBL_VALUE {
            get {
                return ResourceManager.GetString("CAP_LBL_VALUE", resourceCulture);
            }
        }
    }
}
